# Generated by Django 5.0.6 on 2024-08-06 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('assistant_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('assistant_name', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('thread_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VectorStores',
            fields=[
                ('vector_store_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('vector_store_name', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('run_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('assistant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI.assistants')),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI.threads')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI.threads')),
            ],
        ),
        migrations.AddField(
            model_name='threads',
            name='video_store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI.vectorstores'),
        ),
        migrations.AddField(
            model_name='assistants',
            name='attached_vector_store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI.vectorstores'),
        ),
    ]
