# Generated by Django 5.0.6 on 2024-08-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistants',
            name='attached_vector_store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AI.vectorstores'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='video_store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AI.vectorstores'),
        ),
    ]
