# Generated by Django 5.0.6 on 2024-08-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0004_assistants_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('information', models.CharField(max_length=100)),
            ],
        ),
    ]
